 ---
- name: Crear nueva VM en Hyper-V
  hosts: hyperv
  gather_facts: no

  tasks:
    - name: Crear máquina virtual base
      community.windows.win_hyperv:
        name: "vm-base-dev"
        generation: 2
        memory_mb: 2048
        vcpus: 2
        switch_name: "DEV-Switch"
        state: present
        new_disk_size_gb: 20
        new_disk_path: "C:\\Hyper-V\\Virtual Hard Disks\\vm-base-dev.vhdx"
        secure_boot: off

    - name: Mostrar estado de la VM creada
      win_shell: |
        Get-VM -Name "vm-base-dev" | Select Name, State, MemoryAssigned, Uptime
      register: vm_status

    - name: Log de la VM en AWX
      debug:
        var: vm_status.stdout_lines


